---
title: 'Rejecting the Null Hypothesis'
author: "Frederick Anyan"
date: 2023-05-07
categories: [Null hypothesis, Sample statistics, Population parameters]
---

Rejecting the null hypothesis is useful for drawing inferences in the sample as it allows the researcher to conclude about whether or not there is a statistically significant effect, difference or relationship between variables in the population.

Researchers start their research by creating a null hypothesis, which is typically the assumption that there is no significant effect, difference or relationship between the variables in the population. Researchers then collect data from a sample of the population and use statistical tests to determine whether the sample data provides enough evidence to reject the null hypothesis in favor of an alternative hypothesis, which typically states that there is a significant effect, difference or relationship between the variables in the population.

If a researcher rejects the null hypothesis in favor of the alternative hypothesis, this means that the researcher can conclude that there is a statistically significant effect, difference or relationship between the variables in the population from which the sample was drawn. Making inferences to the population, even if the researcher only has data from a sample of that population, is because the researcher has determined that the observed results are unlikely to have occurred by chance, and so the results are representative of the population as a whole. [See here](https://frederickanyan.github.io/quantposts/null%20hypothesis%20testing/)

## Example

<ul>Let's say that a researcher starts with a null hypothesis that there is no relationship between attending lectures and exam anxiety, and collects data from 750 students of NTNU. If a correlation test shows a very low p-value, say p < 0.05, this means that it is very unlikely that the results of the correlation test could have occurred by chance if the null hypothesis was true. Since the p-value, or the probability of observing the results or one that is more extreme given the null hypothesis, is less than the significance level o alpha, researchers reject the null hypothesis for the the alternative hypothesis, which states that there is a significant relationship or effect between the variables being tested - that is, the observed relationship in the sample data reflects true effect or relationship in the population.</ul>

In our example, by rejecting the null hypothesis, the researcher concludes that attending lectures has an effect on exam anxiety, and that this is very unlikely to have occurred by chance if the null hypothesis was true. In this way, the relationship between attending lectures and exam anxiety in the sample of 750 students reflects a true effect in the population of all NTNU students from which the sample of 750 students was drawn. This is an inference because the researcher did not study the population of all NTNU students, but the correlation test in the sample of 750 has provided enough evidence to make a conclusion about the population of all NTNU students.

