---
title: 'Null Hypothesis Testing'
author: "Frederick Anyan"
date: 2023-05-01
categories: [Null hypothesis, Sample statistics, Population parameters]
---

Researchers start their research by creating a null hypothesis, which is the assumption that there is no difference or relationship between the variables being tested. They then collect data and use statistical tests to determine if the data is consistent with the null hypothesis, or if there is enough evidence to reject the null hypothesis. Formally approaching the decision to retain or reject the null hypothesis is called Null Hypothesis Significance Testing. 

A researcher may select a sample of 750 students from the population of _all NTNU students_ to investigate the relationship between attending lectures and exam anxiety. Ideally, the researcher wants to make conclusions about the population of all NTNU students using _sample statistics_ which is computed based on the sample of 750 students. A sample statistic is a numerical summary from the sample data. Here, the mean of exam anxiety for the 750 students or the correlation between attending lectures and exam anxiety for the 750 students is a sample statistic. Its corresponding numeric value for all NTNU students is called a _parameter (or population parameter)_. Although the researcher works with a sample of 750 students, the ultimate interest is in the population of all NTNU students. But the parameter value is unknown unless the researcher can gather all NTNU students.

_So, what does the researcher do?_

The researcher uses sample statistics as estimates for the corresponding population parameters. But this has some problems due to sampling error or random variability. This happens because whenever the researcher samples different groups of 750 students, the researcher may observe a mean of 4.50 for exam anxiety in Group 1 and 5.20 in Group 2 and yet still 3.75 in Group 3. This random variability in a sample statistic such as the mean of exam anxiety from sample to sample is called sampling error. 

_So, what does this mean for the researcher´s conclusions?_

If the researcher makes conclusions based on the sample of 750 students, it will not be guaranteed that the conclusion will be observed in the population of all NTNU students as we have seen with sampling error. It could be that the mean of exam anxiety is not even close to any of the sample means and it could also be that the relationship between attending lectures and exam anxiety observed in the sample of 750 students, will not exist and that there will be no relationship between attending lectures and exam anxiety at all in the population. This would mean that the observed relationship between attending lectures and exam anxiety in the sample of 750 students is just due to sampling error or occurred by chance. 

So, null hypothesis testing is a statistical technique used to determine if the results of a study occurred by chance, or if they are a true effect in the population.

There are many different ways to make the decision to reject the null hypothesis (or fail to reject the null hypothesis), but the general idea is based on the observed relationship in the sample, based on which the researcher makes inferences to the population. Consequently, the general idea is that:

<ul>
  <li>The observed effect or relationship in the sample data reflects sampling error or very likely occurred by chance. Thus, no true effect or relationship exists in the population.</li>
  <li>The observed effect or relationship in the sample data reflects a true effect or relationship in the population. Thus, it is very unlikely to have occurred by chance.</li> 
</ul>

Let's say that a researcher starts with a null hypothesis that there is no relationship between attending lectures and exam anxiety, and collects data from 750 students of NTNU. The researcher must first choose a level of significance (such as 0.05) that represents _the proportion of times (that, if the null hypothesis is true), a researcher will mistakenly reject the null hypothesis, or put simply, the probability of rejecting the null hypothesis in the long run if it is actually true._

If the null hypothesis is indeed true (that, there is no relationship between attending lectures and exam anxiety), and a researcher mistakenly rejects it (therefore says that, there is a relationship between attending lectures and exam anxiety), this is called making a Type-1 error. So, the researcher mistakenly concludes that there is something (or there is an effect or relationship) when there is nothing (no effect or no relationship). Thus, the level of significance or alpha can also be understood as the Type-1 error rate.  
If the p-value is less than the level of significance, the researcher can conclude that there is evidence to reject the null hypothesis. For example, if a correlation test shows a very low p-value, say p < 0.05, this means that it is extremely or very unlikely that the results of the correlation test occurred by chance if the null hypothesis was true. _The p-value is the probability of observing the sample data or one that is more extreme, if the null hypothesis was true._ 

When the p-value, or the probability of observing the results given the null hypothesis, is less than the significance level, the researcher rejects the null hypothesis in favour of the alternative hypothesis, which states that there is a significant relationship or effect between the variables being tested - that is, the observed relationship in the sample data reflects true effect or relationship in the population. So, there is a significant relationship between attending lectures and exam anxiety in NTNU students.

Rejecting the null hypothesis doesn't necessarily 'prove' that the alternative hypothesis is true. It simply means that based on the available evidence - that is, based on the sample data, it is more likely that there is a relationship between attending lectures and exam anxiety than that there isn't. The decision to reject the null hypothesis is based on several factors, including the significance level, or alpha, which specifies the maximum probability of falsely rejecting the null hypothesis if it is actually true in the population.  


