---
title: 'Adolescent stress and symptoms of anxiety and depression: Resilience explains and differentiates the relationships'
date: 2016-10-01
categories: [Mental Health, Resilience Theory, Vulnerability-Stress Theory] 
---

**Background**
Some adolescents exhibit resilience even in the face of high levels of stress exposure. Despite this relationship, studies that investigate explanations for how resilience interacts with risk to produce particular outcomes and why this is so are lacking. The effect of resilience across the relationship between stress and symptoms of anxiety and stress and symptoms of depression was tested to provide explanations for how resilience interacts with stress and symptoms of anxiety, and depression.

**Method**
In a cross-sectional survey, 533 Ghanaian adolescents aged 13–17 years (M=15.25, SD=1.52), comprising 290 girls and 237 boys completed the Resilience Scale for Adolescents, Adolescent Stress Questionnaire, Spielberger State Anxiety Inventory, and Short Mood Feeling Questionnaire. Mediation and moderation analyses were conducted.

**Results**
The results indicated that resilience partially mediated the relationship between stress, and symptoms of anxiety, and depression. Effects of stress were negatively associated with resilience, and positively associated with symptoms of anxiety and depression. In a differential moderator effect, resilience moderated the relationship between stress and symptoms of depression but not stress and symptoms of anxiety.

**Limitations**
Although the findings in this study are novel, they do not answer questions about protective mechanisms or processes.

**Conclusions**
Evidence that resilience did not have the same effect across stress, and symptoms of anxiety and depression may support resilience as a dynamic process model. Access to different levels of resilience shows that enhancing resilience while minimizing stress may improve psychiatric health in adolescents' general population.

[Read more](https://doi.org/10.1016/j.jad.2016.05.031)

[Download paper here](http://github.com/frederickanyan/frederickanyan.github.io/files/publications/adolescent_stress.pdf)

