---
title: 'Change in Physical Activity During the Coronavirus Disease 2019 Lockdown in Norway: The Buffering Effect of Resilience on Mental Health'
date: 2020-12-15
categories: [Mental Health, Resilience Theory, Vulnerability-Stress Theory]
---

Imposition of lockdown restrictions during the coronavirus disease 2019 (COVID-19) pandemic was sudden and unprecedented and dramatically changed the life of many people, as they were confined to their homes with reduced movement and access to fitness training facilities. Studies have reported significant associations between physical inactivity, sedentary behavior, and common mental health problems. This study investigated relations between participants’ reports of change in physical activity (PA; i.e., Reduced PA, Unchanged PA, or Increased PA) and levels of anxiety and depression symptoms during the COVID-19 pandemic lockdown in Norway in the time period from March 12, 2020 to June 15, 2020. The relations between age and gender and levels of anxiety and depression symptoms as well as how different levels of resilience influenced the relation between changes in PA and levels of anxiety and depression symptoms were also investigated. A cross-sectional survey design was used. Participants (N = 1,314; females = 31%) were members of an endurance sports organization aged between 18 and 81 years (M = 49 years; SD = 11.50 years). Participants completed the Resilience Scale for Adults and the Hospital Anxiety and Depression Scale and reported their changes in PA after lockdown restrictions were implemented on March 12, 2020. Regression analysis, independent samples t-test, and two-way multivariate analysis of variance were conducted. Reduced PA was associated with a higher risk of anxiety and depression symptoms. Younger participants in Reduced PA and Unchanged PA subgroups scored significantly higher on levels of anxiety symptoms and significantly higher on depression symptoms in Unchanged PA subgroup. Females in Unchanged PA and Increased PA subgroups scored significantly higher on levels of anxiety symptoms, whereas no gender differences were found for depression symptoms. The main and interaction effects of change in PA and resilience were significantly associated with depression symptoms. For anxiety symptoms, only the main effect of resilience, but not PA, and the interaction effect were significant. Results further showed that resilience was an important factor that influenced the levels of change in PA. High levels of resilience were associated with lower anxiety and depression symptoms in Reduced, Unchanged, and Increased PA subgroups during the COVID-19 lockdown. Promoting PA while boosting resilience factors such as confidence in own ability and drawing on the social support of even reduced social networks or connections while under lockdown can protect against common mental health problems.

[Read more](https://doi.org/10.3389/fpsyg.2020.598481)

[Download](Change-physical-activity.pdf)