---
title: 'Co-creation and regional adaptation of a resilience-based universal whole-school program in five European regions'
date: 2020-10-29
categories: [Resilience, Co-creation, UPRIGHT]
---

The co-creation of educational services that promote youth resilience and mental health is still scarce. UPRIGHT (Universal Preventive Resilience Intervention Globally implemented in schools to improve and promote mental Health for Teenagers) is a research and intervention program in the Basque Country (Spain), Trentino (Italy), Low Silesia (Poland), Denmark and Reykjavik (Iceland). UPRIGHT implemented a co-creation research process whose results, outcomes and policy implications are presented here. The co-creation had a mixed-methods participatory research design with nine specific objectives linked to paired strategies of inquiry for adolescents, families, teachers and school staff. The overarching objective was to generate a valid and feasible regional adaptation strategy for UPRIGHT intervention model. Participants answered surveys (n = 794) or attended 16 group sessions (n = 217). The results integrate quantitative and qualitative information to propose a regional adaptation strategy that prioritizes resilience skills, adolescents’ concerns, and preferred methods for implementation across countries and in each school community. In conclusion, a whole-school resilience program must innovate, include and connect different actors, services and communities, and must incorporate new technologies and activities outside the classroom. A participatory co-creation process is an indispensable step to co-design locally relevant resilience interventions with the involvement of the whole-school community.

[Read more](https://doi.org/10.1177/1474904120947890)

