---
title: 'The coping mechanism and strategies of hypertension patients in Ghana: The role of religious faith, beleifs and practices'
date: 2017-11-06
categories: [Qualitative research, Religious beliefs, Interview]
---
This qualitative study explored the role of religious faith, belief and practice systems in the coping mechanisms and strategies of essential hypertension patients in Accra, Ghana. Six participants were recruited for participation, of which five were Christians and one was a Muslim. Interviews were conducted and interpretative phenomenological analysis was used to analyze the data. Results showed that participants used their religious faith, beliefs and practices as coping resources. Participants used a deferring-collaborative style of religious coping, which seemed to have provided them with an avoidance strategy that protected the participants from conscious confrontation with their illness. Religious faith and beliefs also afforded the participants a sense of coherence that enabled the participants to manage their stress, reflect on their external and internal resources to promote effective coping and adaptive functioning in a health promoting manner. Implications of a deferring-collaborative style of religious coping and religious re-appraisal are discussed.

[Read more](https://doi.org/10.1007/s10943-017-0517-7)