---
title: 'Incidence of mental disorders in the general population aged 1–30 years disaggregated by gender and socioeconomic status'
date: 2023-01-24
categories: [UPRIGHT, Mental health]
---
**Purpose**
The objective of this study was to estimate the incidence and age of onset of mental disorders diagnosed by gender and socioeconomic status (SES) in children, adolescents, and young adults up to 30 years of age in the whole population of the Basque Country (Spain).

**Methods**
All mental health diagnoses documented in Basque Health Service records from 1 January 2003 to 31 December 2018, were classified into eight clusters: anxiety, attention deficit hyperactivity disorder (ADHD), conduct disorders, depression, psychosis/personality disorders, substance use, eating disorders, and self-harm. We calculated incidence and cumulative incidence for each cluster, disaggregated by gender, and socioeconomic status (SES). Poisson regression analyses were performed.

**Results**
Overall, 9,486,853 person-years of observation were available for the 609,281 individuals included. ADHD and conduct disorders were diagnosed in the first decade, anxiety and depression disorders in the second and third decades, and psychosis/personality and substance use in the third. The cumulative incidence at 18 years of age for any type of disorder was 15.5%. The group with low SES had a statistically significantly higher incidence of all eight clusters. The incidence of ADHD, conduct disorders, depression, psychosis/personality disorders, and substance use was higher in males and that of anxiety, eating disorders and self-harm was higher in females.

**Conclusions**
The incidence of mental disorders is high among children, adolescents, and young adults in the Basque Country underlining the need for preventive interventions. Marked differences by gender and SES highlight mental health inequalities, especially for depression and psychosis in low SES males..

[Read more](https://doi.org/10.1007/s00127-023-02425-z)