---
title: 'Prospective Relations Between Dysfunctional Metacognitive Beliefs, Metacognitive Strategies, and Anxiety: Results From a Four-Wave Longitudinal Mediation Model'
date: 2023-02-17
categories: [Mental Health, Metacognitive Theory, Cognitive Theory]
---
The metacognitive model of psychological disorders suggests that emotional disorders are related to maladaptive metacognitive strategies corresponding to underlying dysfunctional metacognitive beliefs. There is substantial empirical evidence supporting a role of metacognition in psychopathology, but fewer studies have evaluated the metacognitive model using longitudinal data and taken into consideration its differentiation between components and how they are hypothesized to be related to each other. Thus, more specific model evaluation is important as it relates to identifying mechanisms of disorder with a potential to provide clinical advances. In the present study, 868 participants took part in a 4-wave survey and reported on metacognitive beliefs and strategies and anxiety symptoms. Two longitudinal mediation models (forward and reversed causation) were run to test temporal precedence and bidirectional relations. The results indicated that metacognitive beliefs significantly predicted metacognitive strategies, which further predicted anxiety symptoms and mediated the indirect effect in the relationship between metacognitive beliefs and anxiety over time. The relationship between metacognitive beliefs and anxiety symptoms over time were bidirectional, but this relationship was not accounted for by metacognitive strategies. These findings largely support central predictions set forward by the metacognitive model and indicate that metacognitions play a preceding and maintaining role in anxiety.

[Read more](https://doi.org/10.1016/j.beth.2023.02.003)

[Download](Metacognition-CAS-Anxiety.pdf)