---
title: 'The network structure of dysfunctional metacognitions, CAS strategies, and symptoms'
date: 2023-04-25
categories: [Anxiety, Metacognitive theory, S-REF model, Metacognitive beliefs, Cognitive Attentional Syndrome, Worry, Rumination]
---
In the metacognitive model of psychological disorders, metacognitive strategies and corresponding underlying metacognitive beliefs intensify and maintain emotional distress symptoms. In the current study, our three objectives were to evaluate and replicate the network structure of dysfunctional metacognitions as assessed with the MCQ-30, to examine its stability when adding relevant covariates in the form of metacognitive strategies (worry and rumination) and symptoms (anxiety and depression), and to evaluate how different sets of dysfunctional metacognitions are more or less strongly linked differently to metacognitive strategies and symptoms. A cross-sectional university sample with a mean age of 26 years (N = 440; Males = 156, Females = 283) completed the Metacognitions Questionnaire–30, Penn State Worry Questionnaire, Ruminative Response Scale, and Hopkins Symptom Checklist. Data were analysed using psychological network analysis in R-studio statistical software. The network structure of dysfunctional metacognitions replicated well with item clusters that correspond to clinically meaningful substructures in the metacognitive model. Negative metacognitive beliefs and beliefs about uncontrollability might have more functional significance in the mutual connections between dysfunctional meta-domains as well as the connections with metacognitive strategies and symptoms. For worry and anxiety, negative beliefs about uncontrollability and corresponding danger of worry were more prominently connected in the network structure. For rumination, cognitive self-consciousness was more prominent, whereas for depression, need for control was more prominently connected. Support was found for mutual interdependence between different sets of dysfunctional metacognitive beliefs, that metacognitive beliefs are linked to but separate from metacognitive strategies, and that these may function together in affecting emotional distress symptoms.

[Read more](https://doi.org/10.1080/23311908.2023.2205258)

