---
title: 'The influence of power shifts in data collection and analysis stages : A focus on qualitative research interview'
date: 2013-06-05
categories: [Qualitative research, Interview, Power asymmetry]
---
This paper analyzes the power relation between the interviewer and the interviewee in the qualitative research interview methodology. The paper sets out to grapple with the extent to which the dynamisms in power shifts influence data collection and analysis in the interview methodology. The exploration of power shifts in the qualitative research interview facilitates comprehensive understanding of the nuances of the data by providing more information about the interviewee and the interviewer. This enhances a deeper discerning into the research process, and the topics discussed. This paper also elaborates on how interviewees as well as interviewers display their countermeasures to each other in the course of the interview situation and presents a greater understanding of the power dynamics that exist between the interviewer and interviewee. Power asymmetry seems to be an exasperating circumstance in the interview methodology as pointed out by the discussions in this article. This article also discusses practical recommendations for minimizing the power dynamic s during data analysis in the qualitative research interview.

[Download paper here](https://github.com/frederickanyan/frederickanyan.github.io//files/publications/power_shifts.pdf)