---
title: 'Prospective relations between loneliness in different relationships, metacognitive beliefs, worry and common mental health problems'
date: 2020-09-09
categories: [Worry, Rumination, Metacognitive theory, Metacognitve beliefs]
---

**Background**
This study investigated prospective relations between loneliness in family, romantic and social relationships and common mental health problems measured as symptoms of anxiety and depression. How these relations are mediated by metacognitive beliefs and worry in a serial mediation model in a full SEM was also tested.

**Materials and methods**
Data were collected at two time points, separated by three months among students at the Norwegian University of Science and Technology. In total, 241 (Females = 65%) students completing both waves of data collection were included for analyses.

**Results**
Loneliness in family relationships was only concurrently associated with worry whereas loneliness in social and romantic relationships showed concurrent and prospective relations. Overall, the results highlighted that for loneliness in social and romantic relationships, their prospective relations with anxiety and depressive symptoms depended on how an individual responded with metacognitive beliefs or worry or both. However, social loneliness might be an exception since it also had a direct effect on levels of depressive symptoms.

**Conclusions**
To prevent or reduce loneliness and common mental health problems, evidence provided show that interventions may incorporate components that target self-focused negative thinking in the form of worry or beliefs about the contents of negative thinking in the form of metacognitive beliefs, underlying loneliness and mental health problems.

[Read more](https://doi.org/10.1016/j.mhp.2020.200186)

