---
title: 'Measuring Resilience Across Participating Regions in the UPRIGHT EU Horizon 2020 Project: Factor Structure and Psychometric Properties of the Resilience Scale for Adolescents'
date: 2021-02-17
categories: [Mental Health, Resilience Theory]
---
Resilience is the process and outcome of healthy adaptation despite significant adversity. Proliferation of research on the resilience construct has led to scientific concerns about the operationalization and measurement of resilience for assessment science and practice. Various studies that have investigated the psychometric properties and construct validity of the Resilience Scale for Adolescents (READ) have yielded inconsistent findings, which could partly be due to variations in the methodological approaches. This study investigated the factor structure and construct validity of the READ in four European regions participating in the Universal Preventive Resilience Intervention Globally Implemented in Schools to Improve and Promote Mental Health for Teenagers (UPRIGHT) project. Participants included adolescents aged 10–15 years from Spain (n = 391, females = 51%), Iceland (n = 379, females = 55%), Italy (n = 460, females = 55%), and Poland (n = 316, females = 51%). The five-factor model of the READ was similar across gender and participating regions. Construct validity of the READ was supported. After establishing construct separability, incremental validity was supported (except for the social competence subscale). The READ is a valid and reliable measure of protective factors involved in resilience and demonstrates promise for cross-cultural applicability. Recommendations for measuring resilience and validating the READ in future investigations are provided.

[Read more](https://doi.org/10.3389/fpsyg.2021.629357)

