---
title: 'Psychometric properties of the Resilience Scale for Adolescents (READ) and Measurement Invariance Across Two Different German-Speaking Samples'
date: 2020-12-24

---
The Resilience Scale for Adolescents (READ) is a highly rated scale for measuring protective factors of resilience. Even though the READ has been validated in several different cultural samples, no studies have validated the READ across samples in German from Switzerland and Germany. The purpose of this study was to explore the construct validity of the German READ version in two samples from two different countries and to test the measurement invariance between those two samples. A German sample (n = 321, M = 12.74, SD = 0.77) and a German-speaking Swiss sample (n = 349, M = 12.67, SD = 0.69) of seventh graders completed the READ, Hopkins Symptom Checklist (HSCL-25), Rosenberg Self-Esteem Scale (RSE), General Self-Efficacy Scale, and Satisfaction with Life Scale (SWL). The expected negative correlations between READ and HSCL-25 and the positive correlations between RSE, self-efficacy, and SWL were supported. Furthermore, the results of the measurement invariance demonstrated that the originally proposed five-dimensional structure is equal in the German and Swiss samples, and it can be assumed that the same construct was assessed by excluding one item. The five-factor, 27-item solution is a valid and reliable self-report measure of protective factors between two German-speaking samples.

[Read more](https://doi.org/10.3389/fpsyg.2020.608677)


