---
title: 'Relevance of well-being, resilience, and health-related quality of life to mental health profiles of European adolescents: results from a cross-sectional analysis of the school-based multinational UPRIGHT project'
date: 2021-08-21
categories: [Mental Health, Resilience Theory]
---
**Purpose**
The existing evidence suggests that a complete evaluation of mental health should incorporate both psychopathology and mental well-being indicators. However, few studies categorize European adolescents into subgroups based on such complete mental health data. This study used the data on mental well-being and symptoms of mental and behavioral disorders to explore the mental health profiles of adolescents in Europe.

**Methods**
Data collected from adolescents (N = 3767; mean age 12.4 [SD = 0.9]) from five European countries supplied the information on their mental well-being (personal resilience, school resilience, quality of life, and mental well-being) and mental and behavioral disorder symptoms (anxiety, depression, stress, bullying, cyber-bullying, and use of tobacco, alcohol, or cannabis). Multiple correspondence analysis and cluster analysis were combined to classify the youths into mental health profiles.

**Results**
Adolescents were categorized into three mental health profiles. The "poor mental health" profile (6%) was characterized by low levels of well-being and moderate symptoms of mental disorders. The "good mental health" profile group (26%) showed high well-being and few symptoms of mental disorders, and the "intermediate mental health" profile (68%) was characterized by average well-being and mild-to-moderate symptoms of mental disorders. Groups with higher levels of well-being and fewer symptoms of mental disorders showed lower rates of behavioral problems. Mental well-being indicators strongly contributed to this classification.

**Conclusion**
Adolescents with the "intermediate" or "poor" mental health profiles may benefit from interventions to improve mental health. Implications for school-based interventions are discussed.

[Read more](https://doi.org/10.1007/s00127-021-02156-z)

[Download](Relevance-of-wellbeing.pdf)