---
title: 'Resilience Moderates Negative Outcome from Stress during the COVID-19 Pandemic: A Moderated-Mediation Approach'
date: 2020-09-04
categories: [Mental Health, Resilience Theory]
---
Resilience refers to an individual’s healthy coping abilities when encountering adverse life events. The COVID-19 pandemic represents a situation with a high amount of stress exposure, which in turn may be associated with negative emotional outcome like depressive symptoms. The current study investigated if resilience moderated the effect of stress on symptoms of depression and if anxiety symptoms mediated this association. An adult sample of community controls completed the Perceived stress scale 14 (PSS-14), the Resilience scale for adults (RSA), the Patient health questionnaire 9 (PHQ-9) and the Generalized anxiety disorder 7 (GAD-7). Independent samples t-test, correlation analyses and moderated mediation analyses were conducted. The results showed that resilience moderated the relations between stress and anxiety symptoms (β = −0.131, p < 0.001) as well as between stress and depressive symptoms (β = −0.068, p < 0.05). In support of a moderated mediation model, resilience moderated the indirect effect of stress on depressive symptom, as confirmed by the index of moderated mediation (IMM = −0.036, p < 0.001; [95% BCa: −0.055, −0.020]). The high resilience subgroup was less affected than the low resilience subgroup by the effect of stress exposure symptoms of depression, mediated by anxiety. The study shows that stress exposure is associated with symptoms of depression, and anxiety mediates this association. Level of resilience differentiates the direct and indirect effect of stress on depression. Knowledge about the effect of stress in response to a pandemic is important for developing treatment and prevention strategies for stress, depression and health-related anxiety.

[Read more](https://doi.org/10.3390/ijerph17186461)



