---
title: 'Resilience patterns of Swiss adolescents before and during the COVID-19 pandemic: a latent transition analysis'
date: 2022-06-24
categories: [Mental Health, Resilience Theory]
---

This study investigated resilience patterns and predictors of these patterns (i.e. gender and migration background) among Swiss early adolescents in times of COVID-19. A total of 317 pupils participated at two time points. We conducted two separate latent class analyses and a latent transition analysis using mental health issues and protective factors as indicators. The results revealed three groups: resilient (high mental health issues, high protective factors), nonresilient (high mental health issues, low protective factors), and untroubled (low mental health issues, high protective factors). The resilient group was the most stable (91% stability), whereas the untroubled was the least stable (69% stability). Boys were more likely to be part of the untroubled group than the other groups at the second time point. Gender at the first time point and migration background at both time points were nonsignificant as predictors. Findings highlight the importance of group-specific research, health promotion, and interventions.

[Read more](https://doi.org/10.1080/02673843.2022.2091938)