---
title: 'Differences in resilience profiles between military veterans and the general population: An exploratory latent profile analysis using the HUNT-4 survey'
date: 2023-11-06
categories: [Mental Health, Resilience Theory]
---
Using latent profile analyses, the current work investigated levels of adverse childhood experiences, symptoms of anxiety and depression and 3 dimensions of relational promotive factors) to identify resilience profiles in a large general population sample (N = 161,622, mean age = 53.02; SD = 17.80; 56.1% females). We then used the same method to identify the resilience profiles of military veterans (N = 386, mean age = 43.47; SD = 10.08; 9.8% females), all of whom had served in Afghanistan. A four-profile-solution was the best fitting for the general population (High resilient 30%, Moderate resilient 13%, Low resilient 53%, Work/social-based resilience 4%), while a three-profile-solution had the best fit in the veteran cohort (Family-based resilience 28%, Work/social-based resilience 62%, Hardy loners 10%). To ground the identified profiles in occupational function, we also checked how they predicted reports of sleep difficulties, job demand and job control. Despite both samples inhabiting a geographic region known for high socioeconomic similarity among residents, we found marked differences in profile-solutions between the military veterans and the general population. Our findings suggests that resilience profiles are highly influenced by cohort characteristics and the specific resources needed to manage a given stressor load. Accordingly, the generalisability of specific protective factors may be low across distinct cohorts, and reliable findings need to be obtained in specific populations as defined by stressor context, sample characteristics, and relevant outcomes.

[Read more](https://onlinelibrary.wiley.com/doi/10.1002/smi.3343)

[Download](resilience_vet_gen.pdf)