---
title: 'Resilience profiles across context: A latent profile analysis in a German, Greek, and Swiss sample of adolescents'
date: 2022-01-27
---

The present study investigated resilience profiles (based on levels of symptoms of anxiety and depression and five dimensions of protective factors) of 1,160 students from Germany (n = 346, 46.0% females, Mage = 12.77, SDage = 0.78), Greece (n = 439, 54.5% females, Mage = 12.68, SDage = 0.69), and Switzerland (n = 375, 44.5% females, Mage = 12.29, SDage = 0.88) using latent profile analyses. We also checked for measurement invariance and investigated the influence of gender and migration on class membership. A three-profile-solution was found for Switzerland (nonresilient 22.1%, moderately resilient 42.9%, untroubled 34.9%), and a four-profile-solution was the best fitting model for Germany (nonresilient 15.7%, moderately resilient 44.2%, untroubled 27.3%, resilient 12.7%) and Greece (nonresilient 21.0%, moderately resilient 30.8%, untroubled 24.9%, resilient 23.3%). Measurement invariance did not hold across the three countries. Profile differences regarding class membership predictions were detected for Germany and Greece, but none for Switzerland. Results implicate that resilience profiles are highly contextually sensitive, and resilience research findings should not be generalized considering the particularity of contexts, people, and outcomes.

[Read more](https://doi.org/10.1371/journal.pone.0263089)

