---
title: 'Measuring Resilience Across Australia and Norway: Validation and Psychometric Properties of the English Version of the Resilience Scale for Adults'
date: 2019-04-05
categories: [Mental Health, Resilience Theory]
---
Resilience has become increasingly important in clinical and health psychology, but only few scales have received good psychometric ratings for assessing various outcomes of resilience. The Resilience Scale for Adults (RSA) is one of the best psychometrically rated scales and has been validated among Norwegian samples. The purpose of this study was to explore the construct validity of the RSA in an English-speaking Australian sample and test measurement invariance between the Australian sample and a Norwegian sample. An Australian sample (N = 781) completed the RSA, Sense of Coherence Scale (SOC-13), Patient Health Questionnaire (PHQ-9), and Generalized Anxiety Disorder Questionnaire (GAD-7). A second sample of Norwegians (N = 320) was included in the analyses of invariance of the RSA across cultures. There were expected negative correlations between RSA and PHQ-9, and between RSA and GAD-7, but positive correlations between RSA and SOC-13. The results indicated that the six-factor measurement model of the RSA is the same in the Australian and Norwegian samples, and respondents from the two cultures understood and interpreted the items in a comparable fashion. Support was found for the cross-cultural validity of the RSA in an English-speaking Australian sample and as a valid and reliable self-report measure of protective factors.

[Read more](https://psycnet.apa.org/doi/10.1027/1015-5759/a000509)

[Download](RSA_Australia.pdf)