---
title: 'Measuring Resilience in Long-term Sick-listed Individuals: Validation of the Resilience Scale for Adults'
date: 2023-03-27

---
Return to work from long-term sick leave is influenced by personal and social factors, which can be measured by resilience, a construct that describe healthy adaptation against adversity. This study aimed to validate the validity and psychometric properties of the resilience scale for adults in a sample of long-term sick-listed individuals, and to investigate measurement invariance when compared with a university student sample. Confirmatory factor analysis was used on a sick-listed sample (n = 687) to identify the scale?s factor structure, and comparison with a university student sample (n = 241) was utilized to determine measurement invariance. Results show that a slightly modified factor structure, in accordance with previous research, achieved acceptable fit in the sick-listed sample, while comparisons with the student sample supported measurement invariance. This means that the study to a large degree support the factor structure of the resilience scale for adults in long-term sick-listed. Furthermore, the results indicate that the scale is similarly understood among long-term sick-listed as in a previously validated student sample. Thus, the resilience scale for adults can be a valid and reliable measure of protective factors in the long-term sickness absence and return to work context, and the subscale and total score can be interpreted similarly in long-term sick-listed as in other populations.

[Read more](https://doi.org/10.1007/s10926-023-10100-y)

