---
title: 'Sick leave and return to work for patients with anxiety and depression: A longitudinal study of trajectories before, during and after work-focused treatment'
date: 2021-09-13

---
**Objectives**
Sick leave due to anxiety and depression is a heterogeneous process constituting a pressing public health issue. This longitudinal study aimed to identify sick leave trajectories among patients before, during and after work-focused treatment, in all 29.5 months. We then aimed to determine the background and clinical characteristics of these trajectory groups.

**Methods** 
Background and clinical data were collected by patient self-report (N=619) in an observational study in a specialised mental healthcare clinic. Sick leave was recorded from national registry data. A latent growth mixture model identified trajectories. Multinomial logistic regression determined differences in background characteristics while a one-way analysis of variance (ANOVA) identified clinical differences.

**Results** 
We identified three trajectories: The ‘Resilient’ group (47.7%) had low sick leave throughout the period. The two other groups (‘Recovery’, 31.8% and ‘High risk’, 20.5%) had similar pretreatment trajectories: lower sick leave one year prior which increased to high sick leave at the start of treatment. After treatment, the ‘Recovery’ group made an almost full return to work while the ‘High risk’ group remained at high sick leave. The two groups with high sick leave had more women and higher age compared with the ‘Resilient’ group. All groups had similar clinical scores at the start of treatment, but the ‘High risk’ groups had residual depressive symptoms at the end of treatment. Effect sizes for anxiety and depression were moderate or large for all groups, (Cohen’s d=0.74–1.81), and 87.2% of the total sample were fully working one year after treatment.

**Conclusion** 
We found three subgroups with distinctly different trajectories. Female gender and higher age were associated with high sick leave at the start of treatment, while residual depressive symptoms at the end of treatment predicted continued sick leave. The study points to the possibility of improving patient outcomes in the future by stratifying and tailoring treatment to patient characteristics.

[Read here](https://doi.org/10.1136/bmjopen-2020-046336)