---
title: 'Development and validation of the theory-driven School Resilience Scale for Adults: Preliminary results'
date: 2020-12-01

---
Resilience is the ability of an individual or community to adapt to life challenges or adversities while maintaining mental health and well-being. In the multi-systemic resilience paradigm, human development and resilience is embedded in adaptive systems and in their interactions. Although the relationship between school systems and adolescents' mental wellbeing is established, there is no agreement on how to recognize and evaluate the most relevant aspects of the school community, acting at collective level, to boost positive socio-emotional and educational outcomes in children and adolescents. This study presents the development and preliminary validation of a new and theory-driven construct and instrument, the School Resilience Scale for Adults (SRS). School Resilience comprises five interrelated constructs (i.e. Positive relationships, Belonging, Inclusion, Participation, and Mental health awareness) connected theoretically to wellbeing and resilience in children and adolescents. The scale development was theory-driven, and the instrument was tested in four European counties in the frame of the UPRIGHT project (Universal Preventive Resilience Intervention Globally implemented in schools to improve and promote mental Health for Teenagers). Overall, 340 adults participated, 129 teachers and school staff, and 211 relatives of teenagers. The sample was randomly split for two studies: (1) an Exploratory Factor analysis (ESEM), and (2) Confirmatory Factor (CFA) analysis. In the exploratory analysis, Chi-Square difference test and model fit indices point towards the five-factor solution over a three-factor solution. The confirmatory study indicated that a five-factor model (RMSEA = 0.038, CFI = 0.96, TLI = 0.95, SRMR = 0.045) was slightly better than a second-order model (RMSEA = 0.046, CFI = 0.94, TLI = 0.93, SRMR = 0.05). Convergent and discriminant validities were partially demonstrated. Alpha and omega reliability coefficients verified the measurement model of the scale. The results confirmed that a multidimensional construct of School Resilience, defined as a collective resilience factor, embedded in the school staff, family members, and adolescents’ interrelated systems can be characterized and measured. Further studies must determine its role in the promotion of adolescents' resilience, mental wellbeing, educational outcomes, and in their positive adaptation in challenging contexts.

[Read more](https://doi.org/10.1016/j.childyouth.2020.105589)

