---
title: 'Stress of home life and gender role socializations, family cohesion, and symptoms of anxiety and depression'
date: 2017-04-01
categories: [Resilience, Stress, Family cohesion]
---
This cross-sectional study investigated the relation of sociocultural prescriptions of gender role socializations to differences in stress at home and to anxiety and depressive symptoms for adolescent girls and boys, with family cohesion as a mediator. A total of 244 boys and 285 girls aged 13–17 years recruited from Accra, Ghana completed the Short Mood Feeling Questionnaire, Spielberger State Anxiety Inventory, Stress of Home Life and Family Cohesion self-report scales in April 2015. In each sample, two mediation analyses were conducted using Structural Equation Modelling. Exposure to stress at home that was perceived to result from sociocultural prescriptions of gender role norms largely accounted for anxiety and depressive symptoms among girls, whereas this relation was non-significant among boys. Significant indirect relations through low family cohesion to anxiety symptoms were observed for girls and boys but not to depressive symptoms for boys. These findings suggest that differences in gender role socializations at home may account for individual differences in associations between exposure to stress at home and anxiety and depressive symptoms as well as explain the differential indirect relations through low family cohesion. Improving family cohesion while reducing stress at home may contribute to reducing stress and thus anxiety and depressive symptoms.

[Download paper here](https://doi.org/10.1080/03630242.2017.1316343)


