---
title: 'Symptoms and prevalence of common mental disorders in a heterogenous outpatient sample: an investigation of clinical characteristics and latent subgroups'
date: 2023-11-03
categories: [Mental Health, Cognitve Theory]
---
Background
Patient-reported outcome measures (PROM) provide clinicians with information about patients’ perceptions of distress. When linked with treatment and diagnostic registers, new information on common mental health disorders (CMHD) and service use, may be obtained, which might be useful clinically and for policy decision-making. This study reports the prevalence of CMHD and their association with PROM severity. Further, subgroups of self-reported symptoms of depression and anxiety were examined, and their association with clinician-assessed mental disorders, functional impairment, and service use.

Methods
In a cohort study of 2473 (63% female) outpatients, CMHD was examined with pre-treatment scores of self-reported depression and anxiety, and the number of assessments and psychotherapy appointments one year after treatment start. Factor mixture modelling (FMM) of anxiety and depression was used to examine latent subgroups.

Results
Overall, 22% of patients with a CMHD had an additional comorbid mood/anxiety disorder, making the prevalence lower than expected. This comorbid group reported higher symptoms of anxiety and depression compared to patients with non-comorbid disorders. FMM revealed three classes: “anxiety and somatic depression” (33%), “mixed depression and anxiety” (40%), and “cognitive depression” (27%). The anxiety and somatic depression class was associated with older age, being single and on sick leave, higher probability of depressive-, anxiety-, and comorbid disorders, having more appointments and higher functional impairment. Although the cognitive depression class had less somatic distress than the mixed depression and anxiety class, they reported more functional impairment and had higher service use.

Conclusion
The results show that higher levels of somatic symptoms of depression could both indicate higher and lower levels of functional impairment and service use. A group of patients with high somatic depression and anxiety was identified, with severe impairment and high service needs. By gaining insights into CMHD factors’ relation with clinical covariates, self-reported risk factors of depression and anxiety could be identified for groups with different levels of aggravating life circumstances, with corresponding service needs. These could be important symptom targets in different groups of patients.

[Read more](https://bmcpsychiatry.biomedcentral.com/articles/10.1186/s12888-023-05314-6)

[Download](symptoms_mixture.pdf)

