---
title: 'Temporal and Reciprocal Relations Between Worry and Rumination Among Subgroups of Metacognitive Beliefs'
date: 2020-09-11
categories: [Mental Health, Metacognitive Theory, Cognitive Theory]
---
Metacognitive theory provides strong foundation for hypothesizing relations between worry and rumination among subgroups of metacognitive beliefs. However, empirical exploration of prospective and reciprocal relations between worry and rumination are lacking. This study investigated the stability and relations between worry and rumination to better understand how they influence each other over time, and how different levels of metacognitive beliefs affect relations between (i) initial and future worry, and initial and future rumination, and (ii) the cross-lag relations between worry and rumination. Overall, 482 (Females = 63%) participants (Mean age = 26 years) participated in a two-wave data collection and completed the Metacognition Questionnaire (MCQ-30), the Ruminative Response Scale and the Penn State Worry Questionnaire (PSWQ). A multigroup two-wave autoregressive cross-lagged model was estimated. Multigroup autoregression analyses revealed that independent of participants being in the high or low metacognition group, initial levels of worry predicted future levels of worry, as was the case for rumination. Multigroup cross-lagged analyses revealed that initial levels of worry did not predict future levels of rumination in both high and low levels of metacognitions. However, initial rumination predicted future levels of worry in the high metacognitions group, which was not the case for the low metacognitions group. Thus, high levels of metacognitions do not only strengthen the relation between both present and future worry, present and future rumination, but also present rumination with future worry. This finding may imply that those with rumination related conditions at present are more likely in the future to show both rumination and worry related conditions. Conversely, those with worry related conditions show future worry related conditions. These findings may have implications for a clinical sample regarding the high complexity of rumination conditions that may proceed with multifinality causal pathways especially for individuals with high levels of metacognitions. This complexity may be a possible explanation for the limited success in other traditional treatment of rumination related conditions and the relatively high relapse rates for such conditions in clinical samples.

[Read more](https://doi.org/10.3389/fpsyg.2020.551503)