---
title: 'Testing the longitudinal effect of metacognitive beliefs on the trajectory of work ability'
date: 2022-11-04
categories: [Mental Health, Metacognitive Theory, Cognitive Theory]
---
There is increasing need to identify factors that contribute to poor work ability with an aim to prevent work related problems such as sick leave and disability pension. In the Metacognitive Control System model, dysfunctional metacognitive beliefs are seen as an underlying factor in psychological vulnerability beyond disorder, and recent studies have reported that metacognitions are associated with work ability and work status. In the present study, we set out to test if there is a prospective relationship between dysfunctional metacognitions and self-assessed work ability. Individuals in working age (M = 37.19; SD = 10.31) participated in a four-timepoint self-report survey (N = 528; 75% females) separated by six weeks between each timepoint. Baseline gender differences and differences between participants by job status were conducted using t-test and one-way ANOVA, respectively. Latent growth curve with covariates assessed the impact of dysfunctional metacognitions on work ability across the four timepoints. Males reported higher work ability. Participants in fulltime job also reported higher work ability followed by those in part-time job, jobseekers, sick leave up to 12 months, and sick leave > 12 months, respectively. Dysfunctional metacognitions predicted work ability over time when controlling for gender, age, physical health status, and three common categories of emotional distress symptoms. This finding suggest that dysfunctional metacognitions are a prospective predictor of work ability beyond health status and implies that these beliefs should be targeted with a view to increasing work ability and thus potentially reduce risk for sick leave and other work-related problems.

[Read more](https://doi.org/10.1007/s12144-022-03912-3)

[Download](Work-ability.pdf)
